# backend/alembic.ini

[alembic]
# эта секция может быть пустой/дефолтной, мы будем работать через -n

[postgres]
script_location = alembic
version_locations = alembic/versions_postgres
version_path_separator = os

# РЕКОМЕНДУЮ sync-драйвер для alembic:
# (поменяй user/pass/host/db под себя; host часто = имя сервиса docker-compose)
sqlalchemy.url = postgresql+psycopg://admin:admin@postgres_databases:5432/fas-project-database

[sqlite]
script_location = alembic
version_locations = alembic/versions_sqlite
version_path_separator = os

# файл SQLite внутри контейнера/проекта:
sqlalchemy.url = sqlite:////app/backend/databases/app.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
