FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    git \
    vim \
    bash-completion \
    curl \
    iputils-ping \
    netcat-traditional \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend

RUN chmod +x /app/backend/entrypoint.sh

ENV PYTHONUNBUFFERED=1

CMD ["/app/backend/entrypoint.sh"]