"""init pg

Revision ID: ad60eb72c6ea
Revises: 
Create Date: 2025-12-16 20:25:31.905395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad60eb72c6ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('report_status', sa.Enum('OK', 'Error', name="report_status"), nullable=True),
    sa.Column('denial_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Reports_created_at'), 'Reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_Reports_employee_id'), 'Reports', ['employee_id'], unique=False)
    op.create_index(op.f('ix_Reports_id'), 'Reports', ['id'], unique=False)
    op.create_index(op.f('ix_Reports_report_status'), 'Reports', ['report_status'], unique=False)
    op.drop_index(op.f('ix_Employees_email'), table_name='Employees')
    op.drop_index(op.f('ix_Employees_first_name'), table_name='Employees')
    op.drop_index(op.f('ix_Employees_id'), table_name='Employees')
    op.drop_index(op.f('ix_Employees_last_name'), table_name='Employees')
    op.drop_index(op.f('ix_Employees_qr_value'), table_name='Employees')
    op.drop_table('Employees')
    op.drop_index(op.f('ix_ImageFiles_hash'), table_name='ImageFiles')
    op.drop_index(op.f('ix_ImageFiles_id'), table_name='ImageFiles')
    op.drop_table('ImageFiles')
    op.drop_index(op.f('ix_Admins_email'), table_name='Admins')
    op.drop_index(op.f('ix_Admins_first_name'), table_name='Admins')
    op.drop_index(op.f('ix_Admins_id'), table_name='Admins')
    op.drop_index(op.f('ix_Admins_last_name'), table_name='Admins')
    op.drop_index(op.f('ix_Admins_qr_value'), table_name='Admins')
    op.drop_table('Admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qr_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Admins_pkey'))
    )
    op.create_index(op.f('ix_Admins_qr_value'), 'Admins', ['qr_value'], unique=True)
    op.create_index(op.f('ix_Admins_last_name'), 'Admins', ['last_name'], unique=False)
    op.create_index(op.f('ix_Admins_id'), 'Admins', ['id'], unique=False)
    op.create_index(op.f('ix_Admins_first_name'), 'Admins', ['first_name'], unique=False)
    op.create_index(op.f('ix_Admins_email'), 'Admins', ['email'], unique=True)
    op.create_table('ImageFiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ImageFiles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ImageFiles_pkey'),
    sa.UniqueConstraint('hash', name='uq_image_files_hash', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_ImageFiles_id'), 'ImageFiles', ['id'], unique=False)
    op.create_index(op.f('ix_ImageFiles_hash'), 'ImageFiles', ['hash'], unique=False)
    op.create_table('Employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qr_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ImageFiles.id'], name=op.f('Employees_image_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Employees_pkey'))
    )
    op.create_index(op.f('ix_Employees_qr_value'), 'Employees', ['qr_value'], unique=True)
    op.create_index(op.f('ix_Employees_last_name'), 'Employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_Employees_id'), 'Employees', ['id'], unique=False)
    op.create_index(op.f('ix_Employees_first_name'), 'Employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_Employees_email'), 'Employees', ['email'], unique=True)
    op.drop_index(op.f('ix_Reports_report_status'), table_name='Reports')
    op.drop_index(op.f('ix_Reports_id'), table_name='Reports')
    op.drop_index(op.f('ix_Reports_employee_id'), table_name='Reports')
    op.drop_index(op.f('ix_Reports_created_at'), table_name='Reports')
    op.drop_table('Reports')
    # ### end Alembic commands ###
