"""init schema

Revision ID: a28b7c79a6b4
Revises:
Create Date: 2025-12-01 20:10:17.037357

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a28b7c79a6b4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("qr_value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Admins_email"), "Admins", ["email"], unique=True)
    op.create_index(
        op.f("ix_Admins_first_name"), "Admins", ["first_name"], unique=False
    )
    op.create_index(op.f("ix_Admins_id"), "Admins", ["id"], unique=False)
    op.create_index(op.f("ix_Admins_last_name"), "Admins", ["last_name"], unique=False)
    op.create_index(op.f("ix_Admins_qr_value"), "Admins", ["qr_value"], unique=True)
    op.create_table(
        "ImageFiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash", name="uq_image_files_hash"),
    )
    op.create_index(op.f("ix_ImageFiles_hash"), "ImageFiles", ["hash"], unique=False)
    op.create_index(op.f("ix_ImageFiles_id"), "ImageFiles", ["id"], unique=False)
    op.create_table(
        "Employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("qr_value", sa.String(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["ImageFiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Employees_email"), "Employees", ["email"], unique=True)
    op.create_index(
        op.f("ix_Employees_first_name"), "Employees", ["first_name"], unique=False
    )
    op.create_index(op.f("ix_Employees_id"), "Employees", ["id"], unique=False)
    op.create_index(
        op.f("ix_Employees_last_name"), "Employees", ["last_name"], unique=False
    )
    op.create_index(
        op.f("ix_Employees_qr_value"), "Employees", ["qr_value"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Employees_qr_value"), table_name="Employees")
    op.drop_index(op.f("ix_Employees_last_name"), table_name="Employees")
    op.drop_index(op.f("ix_Employees_id"), table_name="Employees")
    op.drop_index(op.f("ix_Employees_first_name"), table_name="Employees")
    op.drop_index(op.f("ix_Employees_email"), table_name="Employees")
    op.drop_table("Employees")
    op.drop_index(op.f("ix_ImageFiles_id"), table_name="ImageFiles")
    op.drop_index(op.f("ix_ImageFiles_hash"), table_name="ImageFiles")
    op.drop_table("ImageFiles")
    op.drop_index(op.f("ix_Admins_qr_value"), table_name="Admins")
    op.drop_index(op.f("ix_Admins_last_name"), table_name="Admins")
    op.drop_index(op.f("ix_Admins_id"), table_name="Admins")
    op.drop_index(op.f("ix_Admins_first_name"), table_name="Admins")
    op.drop_index(op.f("ix_Admins_email"), table_name="Admins")
    op.drop_table("Admins")
    # ### end Alembic commands ###
