"""init sqlite

Revision ID: 3dfa14091749
Revises: 
Create Date: 2025-12-16 20:42:45.174398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfa14091749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'Error', name='report_status'), nullable=True),
    sa.Column('denial_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reports_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Reports_status'))
        batch_op.drop_index(batch_op.f('ix_Reports_id'))
        batch_op.drop_index(batch_op.f('ix_Reports_employee_id'))
        batch_op.drop_index(batch_op.f('ix_Reports_created_at'))

    op.drop_table('Reports')
    # ### end Alembic commands ###
